version: "3.9"

services:
  db:
    image: postgres:17
    container_name: kursovaya-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 510141
      POSTGRES_DB: kursovaya
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
